### ISSUE TITLE
ImportError: No module named _driver

### ISSUE THREAD

**Issue by tibbon** [inducer/pycuda#101]
When I run *any* of the example pycuda programs, I get the error of `ImportError: No module named _driver` when trying to do `import pycuda.driver as drv` or similar. Pycuda appeared to install ok. Using the newest Cuda downloads on OS X 10.11. 

```sh

➜  pycuda-2015.1.3  sudo make install                                                                     
Password:
ctags -R src || true
/usr/local/opt/python/bin/python2.7 setup.py install
running install
running bdist_egg
running egg_info
writing requirements to pycuda.egg-info/requires.txt
writing pycuda.egg-info/PKG-INFO
writing top-level names to pycuda.egg-info/top_level.txt
writing dependency_links to pycuda.egg-info/dependency_links.txt
reading manifest file 'pycuda.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cpp' under directory 'bpl-subset/bpl_subset/boost'
warning: no files found matching '*.html' under directory 'bpl-subset/bpl_subset/boost'
warning: no files found matching '*.inl' under directory 'bpl-subset/bpl_subset/boost'
warning: no files found matching '*.txt' under directory 'bpl-subset/bpl_subset/boost'
warning: no files found matching '*.h' under directory 'bpl-subset/bpl_subset/libs'
warning: no files found matching '*.ipp' under directory 'bpl-subset/bpl_subset/libs'
warning: no files found matching '*.pl' under directory 'bpl-subset/bpl_subset/libs'
writing manifest file 'pycuda.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/_cluda.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/_driver.so -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/_mymako.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/_pvt_struct.so -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/autoinit.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/characterize.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/compiler.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
creating build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/compyte/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/compyte/array.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/compyte/dtypes.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte
creating build/bdist.macosx-10.11-x86_64/egg/pycuda/cuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/cuda/pycuda-complex-impl.hpp -> build/bdist.macosx-10.11-x86_64/egg/pycuda/cuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/cuda/pycuda-complex.hpp -> build/bdist.macosx-10.11-x86_64/egg/pycuda/cuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/cuda/pycuda-helpers.hpp -> build/bdist.macosx-10.11-x86_64/egg/pycuda/cuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/cumath.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/curandom.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/debug.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/driver.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/elementwise.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
creating build/bdist.macosx-10.11-x86_64/egg/pycuda/gl
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/gl/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/gl
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/gl/autoinit.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/gl
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/gpuarray.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/reduction.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/scan.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
creating build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/cg.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/coordinate.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/inner.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/operator.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/packeted.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/sparse/pkt_build.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse
copying build/lib.macosx-10.11-x86_64-2.7/pycuda/tools.py -> build/bdist.macosx-10.11-x86_64/egg/pycuda
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/_cluda.py to _cluda.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/_mymako.py to _mymako.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/autoinit.py to autoinit.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/characterize.py to characterize.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/compiler.py to compiler.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte/array.py to array.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/compyte/dtypes.py to dtypes.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/cumath.py to cumath.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/curandom.py to curandom.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/debug.py to debug.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/driver.py to driver.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/elementwise.py to elementwise.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/gl/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/gl/autoinit.py to autoinit.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/gpuarray.py to gpuarray.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/reduction.py to reduction.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/scan.py to scan.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/cg.py to cg.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/coordinate.py to coordinate.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/inner.py to inner.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/operator.py to operator.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/packeted.py to packeted.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/sparse/pkt_build.py to pkt_build.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/tools.py to tools.pyc
creating stub loader for pycuda/_driver.so
creating stub loader for pycuda/_pvt_struct.so
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/_driver.py to _driver.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/pycuda/_pvt_struct.py to _pvt_struct.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pycuda.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pycuda.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pycuda.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pycuda.egg-info/not-zip-safe -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pycuda.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pycuda.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.11-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/pycuda-2015.1.3-py2.7-macosx-10.11-x86_64.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing pycuda-2015.1.3-py2.7-macosx-10.11-x86_64.egg
removing '/usr/local/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-macosx-10.11-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-macosx-10.11-x86_64.egg
Extracting pycuda-2015.1.3-py2.7-macosx-10.11-x86_64.egg to /usr/local/lib/python2.7/site-packages
pycuda 2015.1.3 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/pycuda-2015.1.3-py2.7-macosx-10.11-x86_64.egg
Processing dependencies for pycuda==2015.1.3
Searching for appdirs==1.4.0
Best match: appdirs 1.4.0
Adding appdirs 1.4.0 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for decorator==4.0.6
Best match: decorator 4.0.6
Adding decorator 4.0.6 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for pytest==2.8.7
Best match: pytest 2.8.7
Adding pytest 2.8.7 to easy-install.pth file
Installing py.test-2.7 script to /usr/local/bin
Installing py.test script to /usr/local/bin

Using /usr/local/lib/python2.7/site-packages
Searching for pytools==2016.1
Best match: pytools 2016.1
Adding pytools 2016.1 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for py==1.4.31
Best match: py 1.4.31
Adding py 1.4.31 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for numpy==1.10.2
Best match: numpy 1.10.2
Adding numpy 1.10.2 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for pycuda==2015.1.3
➜  pycuda-2015.1.3  python test.py   
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pycuda.driver as drv
  File "/Users/David/code/pycuda-2015.1.3/pycuda/driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: No module named _driver


```

**Comment by inducer** [comment]
Please use the mailing list for support requests.

**Comment by emmapapa** [comment]
hi, i have the same problem, ImportError: No module named _driver. Have you solve it yet? i need your help, thanks a lot.

**Comment by inducer** [comment]
Same goes for you--please use the mailing list for tech support.

**Comment by makaveli10** [comment]
@inducer I am facing the same issue how to use mailing list ? for this issue!

**Comment by rcx986635** [comment]
Ihave the same problem, ImportError: No module named _driver. 
Anyone has the solution? Thanks .

**Comment by HernandoR** [comment]
same issue on linux, are we still on to mail list?
