### ISSUE TITLE
Autoinit error on MacOS 10.13

### ISSUE THREAD

**Issue by drtpotter** [inducer/pycuda#185]
Hi there,

I've been trying to get pycuda working with MacOS 10.13 (High Sierra). I have a CUDA-capable GPU (NVIDIA GeForce GT 750M) and CUDA 9.2 is installed in its default location /Developer/NVIDIA/CUDA-9.2

I install pycuda with pip. 

```bash
pip install pycuda
```

It appears to install fine but when I try to initialise the pycuda library it has the following problem.

```python
>>> import pycuda.autoinit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/toby/anaconda3/lib/python3.6/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.LogicError
```
It would appear there is a trivial error going on with cuda.init() but I can't seem to find out why.

**Comment by drtpotter** [comment]
Hi Andreas,

Apologies if this message was spamming your inbox, but I do suspect that this issue is a bug with pycuda on the MacOS NVIDIA platform. Happy to repost it on the user forum if you think otherwise.

Kind regards,
Toby

**Comment by inducer** [comment]
If you could, that'd be great. Please do mention if other CUDA programs work. (particularly maybe the driver API example from the SDK)

**Comment by drtpotter** [comment]
Just for those reading this, my problem turned out to be related to Apple's GPU driver which was way behind what was needed for CUDA on MacOS. If the error from pycuda.autoinit was a bit more helpful it would have lead to a faster resolution of the problem. 

Kind regards,
Toby
