### ISSUE TITLE
Multiplication of a gpuarray with a number fails (on Windows 10)

### ISSUE THREAD

**Issue by pdeiml** [inducer/pycuda#200]
Hi,

I use Python 3.6.7 on Windows 10 installed using the anaconda installer and the RTX2080Ti GPU with current driver and CUDA-Toolkit both installed using the Windows 10 installers provided by NVIDIA on its webpage.
Additionally, I installed the python cudatoolkit package with conda.

As a first step, I try to run this simple example

```
import numpy as np
import pycuda.autoinit
import pycuda.gpuarray as gpuarray

a_gpu = gpuarray.to_gpu(np.random.randn(4,4).astype(np.float32))
a_doubled = (2*a_gpu).get()
```
which runs without problems when the last line is commented meaning to me that pycuda and copying an array from host to device works.

But with the last line, the following error occurs
```
Traceback (most recent call last):
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\tools.py", line 426, in context_dependent_memoize
    return ctx_dict[cur_ctx][args]
KeyError: <pycuda._driver.Context object at 0x000001C40A357920>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\test.py", line 6, in <module>
    a_doubled = (2*a_gpu).get()
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\gpuarray.py", line 495, in __rmul__
    return self._axpbz(scalar, 0, result)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\gpuarray.py", line 358, in _axpbz
    func = elementwise.get_axpbz_kernel(self.dtype, out.dtype)
  File "<C:\Users\ii\Anaconda3\lib\site-packages\decorator.py:decorator-gen-8>", line 2, in get_axpbz_kernel
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\elementwise.py", line 425, in get_axpbz_kernel
    "axpb")
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\elementwise.py", line 161, in get_elwise_kernel
    arguments, operation, name, keep, options, **kwargs)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\elementwise.py", line 147, in get_elwise_kernel_and_types
    keep, options, **kwargs)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\elementwise.py", line 75, in get_elwise_module
    options=options, keep=keep)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\compiler.py", line 291, in __init__
    arch, code, cache_dir, include_dirs)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\compiler.py", line 254, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "C:\Users\ii\Anaconda3\lib\site-packages\pycuda\compiler.py", line 55, in preprocess_source
    cmdline, stderr=stderr)
pycuda.driver.CompileError: nvcc preprocessing of C:\Users\ii\AppData\Local\Temp\tmp3vhcp650.cu failed
[command: nvcc --preprocess -arch sm_75 -m64 -Ic:\users\ii\anaconda3\lib\site-packages\pycuda\cuda C:\Users\ii\AppData\Local\Temp\tmp3vhcp650.cu --compiler-options -EP]
```

**Comment by pdeiml** [comment]
The result is:
```
nvcc.exe --preprocess -arch sm_75 -m64 -Ic:C:\Users\ii\Anaconda3\Lib\site-packages\pycuda\cuda\ --compiler-options -EP ./my_source_code.cu
nvcc fatal   : Value 'sm_75' is not defined for option 'gpu-architecture'
```

What does the sm_75 flag exactly mean?

**Comment by inducer** [comment]
Your nvcc is too old to support generating binaries for your GPU.
