### ISSUE TITLE
LogicError while creating SourceModule

### ISSUE THREAD

**Issue by fjarri** [inducer/pycuda#231]
The error can be reproduced by running the example from [the main page of the docs](https://documen.tician.de/pycuda/index.html):

(Ubuntu node on AWS)
```
Traceback (most recent call last):
  File "t.py", line 5, in <module>
    mod = SourceModule("""
  File "/home/ubuntu/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pycuda/compiler.py", line 294, in __init__
    self.module = module_from_buffer(cubin)
pycuda._driver.LogicError
```

(Macos 10.13.6)
```
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    """)
  File "/Users/bogdan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pycuda/compiler.py", line 294, in __init__
    self.module = module_from_buffer(cubin)
pycuda._driver.LogicError: cuModuleLoadDataEx failed: initialization error -
```

I tried it with PyCUDA 2019.1.1, 2019.1.2 and the current git trunk. The strange thing is that it worked fine about a month or two ago, and neither of these machines (as far as I can remember) has been updated since then - OS, CUDA, Python and PyCUDA versions stayed the same. Any ideas?

**Comment by fjarri** [comment]
Nevermind, cache clear helped. Sorry for the disturbance.
