### ISSUE TITLE
pycuda._driver.LogicError: cuInit failed: system has unsupported display driver / cuda driver combination

### ISSUE THREAD

**Issue by firstelfin** [inducer/pycuda#262]
## error
After using the docker image of NVIDIA to create a container, installing **pycuda** in the container encountered the following error:

```shell
$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycuda.autoinit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/trt/lib/python3.6/site-packages/pycuda/autoinit.py", line 5, in <module>
    cuda.init()
pycuda._driver.LogicError: cuInit failed: system has unsupported display driver / cuda driver combination

```

## environment
**ubuntu18.04**：cuda10.2、cudnn7.6.5
**docker container**：cuda10.2、cudnn7.6.5

## issue
@inducer Does pycuda not support using in containers?

**Comment by inducer** [comment]
I haven't tried myself, but I haven't heard any complaints. Can you run other CUDA software in the container? How about Nvidia's SDK samples that use the driver API?

You may have more success asking on the mailing list for people's experience. At any rate, your error message points more towards a software installation problem.
