### ISSUE TITLE
add pycuda.gl in PiPy distribution

### ISSUE THREAD

**Issue by ccarmatic** [inducer/pycuda#470]
**Is your feature request related to a problem? Please describe.**
I have a project which uses both Cuda and OpenGL , and I need `pycuda.gl` functionality

**Describe the solution you'd like**
installing PyCuda via pip should enable me to use `pycuda.gl ` 

**Describe alternatives you've considered**
I tried to build PyCuda with `CUDA_ENABLE_GL = True` in siteconf.py from the zip file downloaded from Github ,but ultimately ran into the following: 
```
    import pycuda.autoinit
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\pycuda-2024.1.2-py3.10-win-amd64.egg\pycuda\autoinit.py", line 7, in <module>
    from pycuda.tools import make_default_context  # noqa: E402
  File "C:\Users\fdasfasdfasd\AppData\Local\Programs\Python\Python310\lib\site-packages\pycuda-2024.1.2-py3.10-win-amd64.egg\pycuda\tools.py", line 33, in <module>
    from pycuda.compyte.dtypes import (  # noqa: F401
ModuleNotFoundError: No module named 'pycuda.compyte'
```

**Additional context**
Maybe I made a mistake when building Boost or PyCuda somewhere along the way?

**Comment by ccarmatic** [comment]
I have installed from the tar file which was downloaded using `pip download pycuda`

Here is my python script:
```
from OpenGL.GL import *
import pygame
import pycuda.driver as cuda
import pycuda.gl

pygame.init()
pygame.display.set_caption('Texture Receiver Example')
pygame.display.set_mode((width, height),
                        pygame.OPENGL | pygame.DOUBLEBUF)
cudagl=pycuda.gl.make_context()
```

which results in this error:
 

> Traceback (most recent call last):
>   File "C:\Users\fdasfasdfasd\Documents\test.py", line 10, in <module>
>     cudagl=pycuda.gl.make_context()
> Boost.Python.ArgumentError: Python argument types in
>     pycuda._driver.make_gl_context()
> did not match C++ signature:
>     make_gl_context(class pycuda::device dev, unsigned int flags=0)
What am I doing wrong?
